### ISSUE TITLE
Uncaught FileNotFoundError in adapters.py line 81

### ISSUE THREAD

**Issue by samihalawa** [Aider-AI/aider#1724]
Aider version: 0.57.1
Python version: 3.12.6
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.46.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 524, in main
    main_model = models.Model(args.model, weak_model=args.weak_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 606, in __init__
    self.get_weak_model(weak_model)
  File "models.py", line 670, in get_weak_model
    self.weak_model = Model(
                      ^^^^^^
  File "models.py", line 589, in __init__
    self.info = self.get_model_info(model)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 609, in get_model_info
    return get_model_info(model)
           ^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 557, in get_model_info
    import requests
  File "__init__.py", line 164, in <module>
    from .api import delete, get, head, options, patch, post, put, request
  File "api.py", line 11, in <module>
    from . import sessions
  File "sessions.py", line 15, in <module>
    from .adapters import HTTPAdapter
  File "adapters.py", line 81, in <module>
    _preloaded_ssl_context.load_verify_locations(
FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by fry69** [comment]
Thank you for filing this issue.

This error is likely due to something gone wrong during installation. Can you please try to install aider separately from other Python modules, e.g. via `pipx` or `venv`?

**Comment by fry69** [comment]
I'm closing this issue for now.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.
