### ISSUE TITLE
Uncaught ValueError in style.py line 76

### ISSUE THREAD

**Issue by dayronmiranda** [Aider-AI/aider#1825]
Aider version: 0.58.0
Python version: 3.10.0rc2
Platform: Windows-10-10.0.26100-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.46.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 501, in main
    git_root = setup_git(git_root, io)
  File "main.py", line 78, in setup_git
    elif io.confirm_ask("No git repo found, create one to track aider's changes (recommended)?"):
  File "io.py", line 526, in confirm_ask
    style = self._get_style()
  File "io.py", line 290, in _get_style
    return Style.from_dict(style_dict)
  File "style.py", line 266, in from_dict
    return cls(list(style_dict.items()))
  File "style.py", line 239, in __init__
    attrs = _parse_style_str(style_str)
  File "style.py", line 172, in _parse_style_str
    attrs = attrs._replace(color=parse_color(part))
  File "style.py", line 76, in parse_color
    raise ValueError(f"Wrong color format {text!r}")
ValueError: Wrong color format 'sonnet'

```

**Comment by fry69** [comment]
Thank you for filing this issue.

Looks like something got messed up in you configuration and you try to set `sonnet` as a color format somehow.

**Comment by fry69** [comment]
I'm closing this issue for now.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.
