### ISSUE TITLE
Uncaught TypeError in repomap.py line 669

### ISSUE THREAD

**Issue by Lesterpaintstheworld** [Aider-AI/aider#1846]
Aider version: <module 'aider.__version__' from 'C:\\Users\\reyno\\ycl\\aider\\aider\\__version__.py'>
Python version: 3.10.6
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.39.2.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 4, in <module>
    main()
  File "main.py", line 727, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1108, in send_message
    chunks = self.format_messages()
  File "base_coder.py", line 1044, in format_messages
    chunks = self.format_chat_chunks()
  File "base_coder.py", line 994, in format_chat_chunks
    chunks.repo = self.get_repo_messages()
  File "base_coder.py", line 627, in get_repo_messages
    repo_content = self.get_repo_map()
  File "base_coder.py", line 609, in get_repo_map
    repo_content = self.repo_map.get_repo_map(
  File "repomap.py", line 127, in get_repo_map
    files_listing = self.get_ranked_tags_map(
  File "repomap.py", line 482, in get_ranked_tags_map
    result = self.get_ranked_tags_map_uncached(
  File "repomap.py", line 513, in get_ranked_tags_map_uncached
    ranked_tags = self.get_ranked_tags(
  File "repomap.py", line 342, in get_ranked_tags
    tags = list(self.get_tags(fname, rel_fname))
  File "repomap.py", line 198, in get_tags
    data = list(self.get_tags_raw(fname, rel_fname))
  File "repomap.py", line 221, in get_tags_raw
    query_scm = get_scm_fname(lang)
  File "repomap.py", line 669, in get_scm_fname
    return resources.files(__package__).joinpath("queries", f"tree-sitter-{lang}-tags.scm")
TypeError: MultiplexedPath.joinpath() takes 2 positional arguments but 3 were given

```

**Comment by fry69** [comment]
Thank you for filing this issue.

Can you please try to install or reinstall aider in a separate Python environment? Either with `venv` or `pipx`?

Please remove the existing environment/aider installation first, e.g. with `pipx`:
```shell
$ pipx uninstall aider-chat
uninstalled aider-chat! ✨ 🌟 ✨
```
```shell
$ pipx install aider-chat
  installed package aider-chat 0.58.1, installed using Python 3.12.6
  These apps are now globally available
    - aider
done! ✨ 🌟 ✨
```

This document may be helpful -> https://aider.chat/docs/troubleshooting/imports.html

**Comment by fry69** [comment]
I'm closing this issue for now.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.
