### ISSUE TITLE
Uncaught ModuleNotFoundError in utils.py line 42

### ISSUE THREAD

**Issue by FidelCastilloAT** [Aider-AI/aider#1917]
Aider version: 0.58.2.dev56+g33b45b68
Python version: 3.11.8
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.44.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 542, in main
    main_model = models.Model(
                 ^^^^^^^^^^^^^
  File "models.py", line 646, in __init__
    res = self.validate_environment()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 845, in validate_environment
    res = litellm.validate_environment(model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 30, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "__init__.py", line 834, in <module>
    from .cost_calculator import completion_cost
  File "cost_calculator.py", line 22, in <module>
    from litellm.llms.anthropic.cost_calculation import (
  File "cost_calculation.py", line 9, in <module>
    from litellm.utils import get_model_info
  File "utils.py", line 42, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

```

**Comment by fry69** [comment]
Thank you for filing this issue.

Can you please try to install or reinstall aider in a separate Python environment? Either with `venv` or `pipx`?

Please remove the existing environment/aider installation first, e.g. with `pipx`:
```shell
$ pipx uninstall aider-chat
uninstalled aider-chat! ✨ 🌟 ✨
```
```shell
$ pipx install aider-chat
  installed package aider-chat 0.58.1, installed using Python 3.12.7
  These apps are now globally available
    - aider
done! ✨ 🌟 ✨
```

This document may be helpful -> https://aider.chat/docs/troubleshooting/imports.html

**Comment by fry69** [comment]
I'm closing this issue for now.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.
