### ISSUE TITLE
Uncaught ValueError in pathlib.py line 682

### ISSUE THREAD

**Issue by L-Sypniewski** [Aider-AI/aider#1933]
Aider version: 0.59.0
Python version: 3.12.3
Platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.39
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.8.0-45-generic (64bit)
Git version: git version 2.43.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 733, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1197, in send_message
    self.reply_completed()
  File "architect_coder.py", line 33, in reply_completed
    editor_coder = Coder.create(**new_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 152, in create
    res = coder(main_model, io, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 350, in __init__
    if self.repo and self.repo.ignored_file(fname):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 340, in ignored_file
    result = self.ignored_file_raw(fname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 346, in ignored_file_raw
    fname_path = Path(self.normalize_path(fname))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 307, in normalize_path
    path = str(Path(PurePosixPath((Path(self.root) / path).relative_to(self.root))))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: '/tmp/tmpcz53mx47/clipboard_image.png' is not in the subpath of '/home/lukasz/Documents/Developer/project'

```

**Comment by fry69** [comment]
Duplicate #1774
