### ISSUE TITLE
Uncaught AttributeError in pathlib.py line 1094

### ISSUE THREAD

**Issue by eun-nic** [Aider-AI/aider#1941]
Aider version: 0.59.1
Python version: 3.12.2
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 757, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 767, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 756, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 233, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 208, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 704, in cmd_add
    matched_files = self.glob_filtered_to_repo(word)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 656, in glob_filtered_to_repo
    raw_matched_files = list(Path(self.coder.root).glob(pattern))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1094, in glob
    for p in selector.select_from(self):
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: '_TerminatingSelector' object has no attribute 'select_from'. Did you mean: '_select_from'?

```

**Comment by fry69** [comment]
Thank you for filing this issue.

Can you please elaborate what the circumstances where that lead to this exception?

Anyway, this should be handled more gracefully, so I label it a bug for now.
