### ISSUE TITLE
Uncaught AttributeError in configargparse.py line 1047

### ISSUE THREAD

**Issue by gordonforce** [Aider-AI/aider#1948]
Aider version: 0.59.1
Python version: 3.12.7
Platform: Linux-6.6.46-04023-gef804018a050-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.6.46-04023-gef804018a050 (64bit)
Git version: git version 2.46.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 387, in main
    raise e
  File "main.py", line 382, in main
    args, unknown = parser.parse_known_args(argv)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "configargparse.py", line 938, in parse_known_args
    [self.get_command_line_key_for_unknown_config_file_setting(key)],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "configargparse.py", line 1047, in get_command_line_key_for_unknown_config_file_setting
    key_without_prefix_chars = key.strip(self.prefix_chars)
                               ^^^^^^^^^
AttributeError: 'int' object has no attribute 'strip'

```

**Comment by fry69** [comment]
Duplicate #1931
