### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by rahsheen** [Aider-AI/aider#1965]
Aider version: 0.56.0
Python version: 3.10.4
Platform: macOS-14.4-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.4.0 (64bit)
Git version: git version 2.46.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 698, in main
    if args.lint or args.test or args.commit:
  File "base_coder.py", line 735, in run
    return
  File "base_coder.py", line 778, in run_one
    if self.num_reflections >= self.max_reflections:
  File "base_coder.py", line 1202, in send_message
    content += "\n^C KeyboardInterrupt"
  File "base_coder.py", line 1885, in auto_commit
    return context
  File "repo.py", line 102, in commit
  File "repo.py", line 187, in get_commit_message
    ]
  File "sendchat.py", line 38, in wrapper
    retry_exceptions(),
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.chat.AnthropicError,
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

**Comment by fry69** [comment]
Thank you for filing this issue.

The fix is in the latest version (`0.59.1`), please update aider with
```
aider --upgrade
```
Please do not forget to exit and restart aider after it updated itself.

Duplicate #1278

**Comment by rahsheen** [comment]
That's weird since the first thing aider did when I ran it was to update. Maybe it should exit and restart on its own as well?

**Comment by fry69** [comment]
> That's weird since the first thing aider did when I ran it was to update. Maybe it should exit and restart on its own as well?

It does so in newer version, can't fix installation in the past though.
