### ISSUE TITLE
Uncaught RuntimeError in SentenceTransformer.py line 652

### ISSUE THREAD

**Issue by ericie** [Aider-AI/aider#1970]
Aider version: 0.59.1
Python version: 3.12.7
Platform: macOS-14.7-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.33.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 757, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 767, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 756, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 233, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 208, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 972, in cmd_help
    self.help = Help()
                ^^^^^^
  File "help.py", line 120, in __init__
    index = get_index()
            ^^^^^^^^^^^
  File "help.py", line 105, in get_index
    index = VectorStoreIndex(nodes, show_progress=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 75, in __init__
    super().__init__(
  File "base.py", line 77, in __init__
    index_struct = self.build_index_from_nodes(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 307, in build_index_from_nodes
    return self._build_index_from_nodes(nodes, **insert_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 278, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "base.py", line 231, in _add_nodes_to_index
    nodes_batch = self._get_node_with_embedding(nodes_batch, show_progress)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 138, in _get_node_with_embedding
    id_to_embed_map = embed_nodes(
                      ^^^^^^^^^^^^
  File "utils.py", line 138, in embed_nodes
    new_embeddings = embed_model.get_text_embedding_batch(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 335, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 277, in _get_text_embeddings
    return self._embed(texts, prompt_name="text")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base.py", line 215, in _embed
    emb = self._model.encode(
          ^^^^^^^^^^^^^^^^^^^
  File "SentenceTransformer.py", line 652, in encode
    all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
                                 ^^^^^^^^^^^
RuntimeError: Numpy is not available

```

**Comment by fry69** [comment]
Thank you for filing this issue.

Can you please try to install or reinstall aider in a separate Python environment? Either with `venv` or `pipx`?

Please remove the existing environment/aider installation first, e.g. with `pipx`:
```shell
$ pipx uninstall aider-chat
uninstalled aider-chat! ✨ 🌟 ✨
```
```shell
$ pipx install aider-chat
  installed package aider-chat 0.59.1, installed using Python 3.12.7
  These apps are now globally available
    - aider
done! ✨ 🌟 ✨
```

This document may be helpful -> https://aider.chat/docs/troubleshooting/imports.html
