### ISSUE TITLE
Introduction of PyDub introduces deprecation warning for python 3.13

### ISSUE THREAD

**Issue by ngharrington** [Aider-AI/aider#1980]
### Issue

I would like to call it to your attention that the [introduction of pydub as a dependency ](https://github.com/Aider-AI/aider/commit/1cc30a22f9df7be3208f951f5c113431809cc957#diff-2d88edd924033b49783dcb4f93a0ed0ec8aae0b6aac3bad984a2c1d323b93c37R5) we have introduced standard library dependencies that will be deprecated in python 3.13. 

```bash
$ python -B -Werror $(which aider)
Traceback (most recent call last):
  File "/home/neal/workspace/aider-sandbox/venv312/bin/aider", line 5, in <module>
    from aider.main import main
  File "/home/neal/workspace/aider-sandbox/venv312/lib/python3.12/site-packages/aider/main.py", line 16, in <module>
    from aider.coders import Coder
  File "/home/neal/workspace/aider-sandbox/venv312/lib/python3.12/site-packages/aider/coders/__init__.py", line 1, in <module>
    from .architect_coder import ArchitectCoder
  File "/home/neal/workspace/aider-sandbox/venv312/lib/python3.12/site-packages/aider/coders/architect_coder.py", line 2, in <module>
    from .ask_coder import AskCoder
  File "/home/neal/workspace/aider-sandbox/venv312/lib/python3.12/site-packages/aider/coders/ask_coder.py", line 2, in <module>
    from .base_coder import Coder
  File "/home/neal/workspace/aider-sandbox/venv312/lib/python3.12/site-packages/aider/coders/base_coder.py", line 22, in <module>
    from aider.commands import Commands
  File "/home/neal/workspace/aider-sandbox/venv312/lib/python3.12/site-packages/aider/commands.py", line 16, in <module>
    from aider import models, prompts, voice
  File "/home/neal/workspace/aider-sandbox/venv312/lib/python3.12/site-packages/aider/voice.py", line 18, in <module>
    from pydub import AudioSegment  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neal/workspace/aider-sandbox/venv312/lib/python3.12/site-packages/pydub/__init__.py", line 1, in <module>
    from .audio_segment import AudioSegment
  File "/home/neal/workspace/aider-sandbox/venv312/lib/python3.12/site-packages/pydub/audio_segment.py", line 11, in <module>
    from .utils import mediainfo_json, fsdecode
  File "/home/neal/workspace/aider-sandbox/venv312/lib/python3.12/site-packages/pydub/utils.py", line 15, in <module>
    import audioop
DeprecationWarning: 'audioop' is deprecated and slated for removal in Python 3.13
```

This is in addition to the "invalid escape warnings" the dependency introduces as well, as described here: https://github.com/Aider-AI/aider/issues/1722#issuecomment-2400879113

### Version and model info

Aider: 0.59.1

**Comment by ngharrington** [comment]
Discussion of the deprecation of audioop and it's impact on pydub here https://github.com/jiaaro/pydub/issues/725

**Comment by fry69** [comment]
FYI: There is -> https://pypi.org/project/audioop-lts/ thanks to https://github.com/Rapptz/discord.py relying on that too.

Also aider currently requires Python 3.9 - 3.12, 3.13 is not yet supported. See here -> https://github.com/Aider-AI/aider/blob/main/pyproject.toml#L23

**Comment by paul-gauthier** [comment]
I'm labeling this issue as stale because it has been open for 2 weeks with no activity. If there are no additional comments, it will be closed in 7 days.

**Comment by paul-gauthier** [comment]
I'm closing this issue because it has been stalled for 3 weeks with no activity. Feel free to add a comment here and we can re-open it. Or feel free to file a new issue at any time.
