### ISSUE TITLE
Uncaught AttributeError in format_settings.py line 6

### ISSUE THREAD

**Issue by jose70539** [Aider-AI/aider#2049]
Aider version: 0.59.2.dev
Python version: 3.12.6
Platform: macOS-15.0-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 24.0.0 (64bit)
Git version: git version 2.39.5 (Apple Git-154)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "main.py", line 854, in <module>
    status = main()
             ^^^^^^
  File "main.py", line 553, in main
    cmd_line = scrub_sensitive_info(args, cmd_line)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "format_settings.py", line 6, in scrub_sensitive_info
    if text and args.anthropic_api_key:
                ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'anthropic_api_key'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. 

How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
