### ISSUE TITLE
Uncaught RecursionError in linter.py line 264

### ISSUE THREAD

**Issue by fidelsalz** [Aider-AI/aider#2148]
Aider version: 0.60.0
Python version: 3.12.7
Platform: Linux-6.10.10-arch1-1-x86_64-with-glibc2.40
Python implementation: CPython
Virtual environment: No
OS: Linux 6.10.10-arch1-1 (64bit)
Git version: git version 2.47.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 776, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1223, in send_message
    lint_errors = self.lint_edited(edited)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1320, in lint_edited
    errors = self.linter.lint(self.abs_root_path(fname))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 108, in lint
    lintres = basic_lint(rel_fname, code)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 224, in basic_lint
    errors = traverse_tree(tree.root_node)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 264, in traverse_tree
    errors += traverse_tree(child)
              ^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 264, in traverse_tree
    errors += traverse_tree(child)
              ^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 264, in traverse_tree
    errors += traverse_tree(child)
              ^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 989 more times]
RecursionError: maximum recursion depth exceeded

```

**Comment by fidelsalz** [comment]
Aider was writing an sql code that had to repeat 400 times the same commands just changing single words on it. Apparently it reached the final but gave error before saving the file.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
