### ISSUE TITLE
Uncaught ModuleNotFoundError in function_base.py line 543

### ISSUE THREAD

**Issue by DMTarmey** [Aider-AI/aider#2198]
Aider version: <module 'aider.__version__' from '/home/dmtarmey/AiderProjects/aider-env/lib/python3.12/site-packages/aider/__version__.py'>
Python version: 3.12.7
Platform: Linux-6.6.58-1-lts-x86_64-with-glibc2.40
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.6.58-1-lts (64bit)
Git version: git version 2.47.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 777, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1108, in send_message
    chunks = self.format_messages()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1044, in format_messages
    chunks = self.format_chat_chunks()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 994, in format_chat_chunks
    chunks.repo = self.get_repo_messages()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 627, in get_repo_messages
    repo_content = self.get_repo_map()
                   ^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 599, in get_repo_map
    repo_content = self.repo_map.get_repo_map(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 127, in get_repo_map
    files_listing = self.get_ranked_tags_map(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 491, in get_ranked_tags_map
    result = self.get_ranked_tags_map_uncached(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 522, in get_ranked_tags_map_uncached
    ranked_tags = self.get_ranked_tags(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 399, in get_ranked_tags
    ranked = nx.pagerank(G, weight="weight", **pers_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "backends.py", line 412, in __call__
    return self.orig_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pagerank_alg.py", line 110, in pagerank
    return _pagerank_scipy(
           ^^^^^^^^^^^^^^^^
  File "pagerank_alg.py", line 452, in _pagerank_scipy
    import numpy as np
  File "__init__.py", line 144, in <module>
    from . import core
  File "__init__.py", line 100, in <module>
    from . import _add_newdocs
  File "_add_newdocs.py", line 4973, in <module>
    add_newdoc('numpy.core._multiarray_tests', 'format_float_OSprintf_g',
  File "function_base.py", line 543, in add_newdoc
    new = getattr(__import__(place, globals(), {}, [obj]), obj)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'numpy.core._multiarray_tests'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. 

How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by DMTarmey** [comment]
Im using linux endevour os
________________________________
