### ISSUE TITLE
How to run aider fixed command WITHOUT triggering file edits?

### ISSUE THREAD

**Issue by tkruse** [Aider-AI/aider#2246]
### Issue

I am trying aider for the first time, and what I am trying to set up is a configuration for tasks my teammates can use without getting much distraction from aider chat features. 

But I am stuck with aider either crashing or trying to modify the project files.

So here is my current attempt for getting a code review output

```
# CONVENTIONS.md 
# ... Some code guidelines here ...
```

```
#.aider/MR_REVIEW.txt
/run git diff main --exit-code
```

```
read:
  - CONVENTIONS.md

#.aider/MR_REVIEW.conf.yml
load: .aider/MR_REVIEW.txt

# my attempts at stopping aider from modifying files
dry-run: true
exit: true
suggest-shell-commands: false
cache-prompts: false
yes-always: true

message: please review the diff above in the chat with respect to our conventions. Do not mention anything that already follows our conventions. List specific changes in the diff that violate our conventions. If there are no violations, please approve the MR.
```

then running: `aider --config .aider/MR_REVIEW.conf.yml` I get a useful output, but aider then always continues to do:
```
...
Add the output to the chat?
(Y)es/(n)o/message with instructions: yes

Based on the provided summaries and the coding conventions, here are the potential violations: 

... e.g. In [...], the Exception is thrown without a formatted message.

Tokens: 2.1k sent, 314 received. Cost: $0.0083 message, $0.0083 session.
To address the potential violations you mentioned, we need to make changes to the files...

To refactor the code according to the conventions, we will:   ...

Let's start with the [...] file:       
```

**So how can I prevent aider from continuing with the code refactoring?**

I have already tried using /ask in the messages file instead, like:
```
#.aider/MR_REVIEW.txt
/run git diff main --exit-code
/ask please review the diff above in the chat with respect to our conventions. Do not mention anything that already follows our conventions. List specific changes in the diff that violate our conventions. If there are no violations, please approve the MR.
```

This might work, but sadly this fails in the end with:
```
# Uncaught SwitchCoder in commands.py line 1044

Aider version: 0.61.0
Python version: 3.12.6
Platform: macOS-14.7-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.46.2

An uncaught exception occurred:

Traceback (most recent call last):
  File "aider-wrapper.py", line 37, in <module>
    main()
  File "main.py", line 793, in main
    commands.cmd_load(args.load)
  File "commands.py", line 1287, in cmd_load
    self.run(cmd)
  File "commands.py", line 236, in run
    return self.do_run(command, rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 208, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 1017, in cmd_ask
    return self._generic_chat_command(args, "ask")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 1044, in _generic_chat_command
    raise SwitchCoder(
aider.commands.SwitchCoder


Please consider reporting this bug to help improve aider!
Open a GitHub Issue pre-filled with the above error in your browser? (Y/n) n
Traceback (most recent call last):
  File "/Users/tkruse/.indeed-dev-tools/ai4dp/setup-ai4dp/lib/aider-wrapper.py", line 37, in <module>
    main()
  File "/Users/tkruse/.aider/venv/lib/python3.12/site-packages/aider/main.py", line 793, in main
    commands.cmd_load(args.load)
  File "/Users/tkruse/.aider/venv/lib/python3.12/site-packages/aider/commands.py", line 1287, in cmd_load
    self.run(cmd)
  File "/Users/tkruse/.aider/venv/lib/python3.12/site-packages/aider/commands.py", line 236, in run
    return self.do_run(command, rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tkruse/.aider/venv/lib/python3.12/site-packages/aider/commands.py", line 208, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "/Users/tkruse/.aider/venv/lib/python3.12/site-packages/aider/commands.py", line 1017, in cmd_ask
    return self._generic_chat_command(args, "ask")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tkruse/.aider/venv/lib/python3.12/site-packages/aider/commands.py", line 1044, in _generic_chat_command
    raise SwitchCoder(
aider.commands.SwitchCoder
!!! BASH reports ERROR: shell returned 1

```

(same as https://github.com/Aider-AI/aider/issues/2246)

### Version and model info

Aider version: 0.61.0
Python version: 3.12.6
Platform: macOS-14.7-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.46.2

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, it would be hard for me to help debug aider scripting problems. Not all `/` commands are supported.
