### ISSUE TITLE
Uncaught FileNotFoundError in <frozen posixpath> line 423

### ISSUE THREAD

**Issue by QTPah** [Aider-AI/aider#2248]
Aider version: 0.57.1
Python version: 3.12.3
Platform: Linux-6.8.0-47-generic-x86_64-with-glibc2.39
Python implementation: CPython
Virtual environment: No
OS: Linux 6.8.0-47-generic (64bit)
Git version: git version 2.43.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 344, in main
    default_config_files = [conf_fname.resolve()]  # CWD
                            ^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1242, in resolve
    s = self._flavour.realpath(self, strict=strict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 436, in realpath
  File "<frozen posixpath>", line 423, in abspath
FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by paul-gauthier** [comment]
This should be fixed in the latest version. You can get it like this:

```
aider --upgrade

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed aider-chat
```

If you have a chance to try it, let me know if it works better for you.
