### ISSUE TITLE
Uncaught Exception `b''` with Ollama

### ISSUE THREAD

**Issue by LuminousPath** [Aider-AI/aider#2257]
### Issue

getting an error when trying to use Ollama locally:

```
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/aider/coders/base_coder.py", line 1184, in send_message
    yield from self.send(messages, functions=self.functions)
  File "/venv/lib/python3.10/site-packages/aider/coders/base_coder.py", line 1491, in send
    yield from self.show_send_output_stream(completion)
  File "/venv/lib/python3.10/site-packages/aider/coders/base_coder.py", line 1558, in show_send_output_stream
    for chunk in completion:
  File "/venv/lib/python3.10/site-packages/litellm/llms/ollama.py", line 428, in ollama_completion_stream
    raise e
  File "/venv/lib/python3.10/site-packages/litellm/llms/ollama.py", line 380, in ollama_completion_stream
    raise OllamaError(
litellm.llms.ollama.OllamaError: b''
```

the query was simply `what is this repo?`

### Version and model info

Aider: 0.62.0
Python: 3.10.15
Platform: Docker
Docker Version: 20.10.27
Model: ollama/deepseek-coder-v2
Ollama: 0.3.13

**Comment by LuminousPath** [comment]
this seems to be an issue specifically with streaming, as turning it off with `--no-stream` seems to remove the error.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Perhaps ollama doesn't support streaming your model?

**Comment by paul-gauthier** [comment]
I'm labeling this issue as stale because it has been open for 2 weeks with no activity. If there are no additional comments, I will close it in 7 days.Note: A [bot script](https://github.com/Aider-AI/aider/blob/main/scripts/issues.py) made these updates to the issue.
