### ISSUE TITLE
Uncaught NotFoundError in exception_mapping_utils.py line 845

### ISSUE THREAD

**Issue by marking** [Aider-AI/aider#2287]
I launched aider in architect mode using the following models:

- Main model: openrouter/google/gemini-pro-1.5 with architect edit format
- Editor model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0 with diff edit format
- Weak model: bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0

I only chose the main model on the command line and set the Editor and Weak model in the configuration file.

I asked aider to combine and simplify 3 powershell scripts into a single powershell script. The architect suggested good changes and handed them off to the editor. When I confirmed that the editor should make the changes by creating the new file, I was presented with the exception.

Aider version: 0.62.1
Python version: 3.12.7
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git information unavailable

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "main.py", line 2582, in completion
    response = bedrock_chat_completion.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "invoke_handler.py", line 811, in completion
    raise BedrockError(
litellm.llms.bedrock.common_utils.BedrockError: Bedrock HTTPX: Unknown provider=us, model=us.anthropic.claude-3-5-haiku-20241022-v1:0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 827, in main
    coder.run()
  File "base_coder.py", line 738, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 781, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1263, in send_message
    self.reply_completed()
  File "architect_coder.py", line 40, in reply_completed
    editor_coder.run(with_message=content, preproc=False)
  File "base_coder.py", line 732, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 781, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1278, in send_message
    saved_message = self.auto_commit(edited)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1979, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, aider_edits=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 110, in commit
    commit_message = self.get_commit_message(diffs, context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 195, in get_commit_message
    commit_message = simple_send_with_retries(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 118, in simple_send_with_retries
    _hash, response = send_completion(**kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 98, in send_completion
    res = litellm.completion(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 1013, in wrapper
    raise e
  File "utils.py", line 903, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 2999, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "exception_mapping_utils.py", line 2116, in exception_type
    raise e
  File "exception_mapping_utils.py", line 845, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: litellm.NotFoundError: BedrockException - Bedrock HTTPX: Unknown provider=us, model=us.anthropic.claude-3-5-haiku-20241022-v1:0

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, it would be hard for me to debug your bedrock model configuration.

**Comment by marking** [comment]
I can try to reproduce this with additional logging enabled if additional logging is available.
________________________________

**Comment by paul-gauthier** [comment]
I'm labeling this issue as stale because it has been open for 2 weeks with no activity. If there are no additional comments, I will close it in 7 days.Note: A [bot script](https://github.com/Aider-AI/aider/blob/main/scripts/issues.py) made these updates to the issue.

**Comment by marking** [comment]
Saving your bot a few days :)
