### ISSUE TITLE
Uncaught FileNotFoundError in repo.py line 171

### ISSUE THREAD

**Issue by anducostin** [Aider-AI/aider#2314]
Aider version: 0.62.1
Python version: 3.11.5
Platform: macOS-15.0.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 24.0.0 (64bit)
Git version: git version 2.47.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "main.py", line 827, in main
    coder.run()
  File "base_coder.py", line 738, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 775, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 764, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 240, in run
    return self.do_run(command, rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 208, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 70, in cmd_model
    raise SwitchCoder(main_model=model)
aider.commands.SwitchCoder

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 838, in main
    coder.show_announcements()
  File "base_coder.py", line 454, in show_announcements
    for line in self.get_announcements():
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 199, in get_announcements
    rel_repo_dir = self.repo.get_rel_repo_dir()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 171, in get_rel_repo_dir
    return os.path.relpath(self.repo.git_dir, os.getcwd())
                                              ^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
