### ISSUE TITLE
Uncaught TypeError in core.pyx line 14

### ISSUE THREAD

**Issue by brooksc** [Aider-AI/aider#2323]
Background: I'm working on a django project.  I've been working on this with both cline and aider.  After working with cline for a while I switched back to aider and tried to do "/run ./manage.py runbot" and it threw this error.

I just added outstanding changes and committed them so it's a clean git status.  I restarted and it failed again with the same error

I just tried a 3rd time and refreshed the map and I'm getting this error

> /map-refresh

Unable to complete map_refresh: __init__() takes exactly 1 argument (2 given)

Next I'll try uninstalling and reinstalling aider-chat.  

I finally fixed it by deleting my virtualenv, recreating it and re-installing everything - and now it's working.  Sorry I didn't keep a copy of the virtualenv to figure out what the issue was with the packages.  
---
Aider version: 0.62.1
Python version: 3.12.3
Platform: macOS-15.2-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 24.2.0 (64bit)
Git version: git version 2.47.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 827, in main
    coder.run()
  File "base_coder.py", line 738, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 781, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1163, in send_message
    chunks = self.format_messages()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1097, in format_messages
    chunks = self.format_chat_chunks()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1047, in format_chat_chunks
    chunks.repo = self.get_repo_messages()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 635, in get_repo_messages
    repo_content = self.get_repo_map()
                   ^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 607, in get_repo_map
    repo_content = self.repo_map.get_repo_map(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 128, in get_repo_map
    files_listing = self.get_ranked_tags_map(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 549, in get_ranked_tags_map
    result = self.get_ranked_tags_map_uncached(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 614, in get_ranked_tags_map_uncached
    tree = self.to_tree(ranked_tags[:middle], chat_rel_fnames)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 697, in to_tree
    output += self.render_tree(cur_abs_fname, cur_fname, lois)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 653, in render_tree
    context = TreeContext(
              ^^^^^^^^^^^^
  File "grep_ast.py", line 47, in __init__
    parser = get_parser(lang)
             ^^^^^^^^^^^^^^^^
  File "core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)

```

**Comment by brooksc** [comment]
It's probably fine to close this out as once I reset my environment I couldn't repro.
