### ISSUE TITLE
Uncaught OSError in _win32_console.py line 403

### ISSUE THREAD

**Issue by deb1265** [Aider-AI/aider#2344]
Aider version: 0.62.1
Python version: 3.12.4
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.42.0.windows.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "base_coder.py", line 1184, in send_message
    yield from self.send(messages, functions=self.functions)
  File "base_coder.py", line 1491, in send
    yield from self.show_send_output_stream(completion)
  File "base_coder.py", line 1597, in show_send_output_stream
    sys.stdout.flush()
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 827, in main
    coder.run()
  File "base_coder.py", line 738, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 781, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1231, in send_message
    self.io.tool_warning("".join(lines))
  File "io.py", line 639, in tool_warning
    self._tool_message(message, strip, self.tool_warning_color)
  File "io.py", line 632, in _tool_message
    self.console.print(message, **style)
  File "console.py", line 1678, in print
    with self:
  File "console.py", line 864, in __exit__
    self._exit_buffer()
  File "console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "console.py", line 2019, in _check_buffer
    self._write_buffer()
  File "console.py", line 2055, in _write_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "_windows_renderer.py", line 19, in legacy_windows_render
    term.write_text(text)
  File "_win32_console.py", line 403, in write_text
    self.flush()
OSError: [Errno 22] Invalid argument

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Are you able to reproduce this error?
