### ISSUE TITLE
Uncaught KeyError in models.py line 1107

### ISSUE THREAD

**Issue by yuhuihu** [Aider-AI/aider#2358]
Aider version: 0.62.1
Python version: 3.10.15
Platform: macOS-14.5-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.5.0 (64bit)
Git version: git version 2.40.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 638, in main
    problem = models.sanity_check_models(io, main_model)
  File "models.py", line 1046, in sanity_check_models
    problem_main = sanity_check_model(io, main_model)
  File "models.py", line 1090, in sanity_check_model
    possible_matches = fuzzy_match_models(model.name)
  File "models.py", line 1107, in fuzzy_match_models
    provider = (attrs["litellm_provider"] + "/").lower()
KeyError: 'litellm_provider'

```

config of .env
```
OPENAI_API_BASE=http://192.168.3.63:1234/v1                                                                                        
OPENAI_API_KEY=lm-studio
AIDER_MODEL=14b@q4_k_m
```

**Comment by paul-gauthier** [comment]
This should be fixed in the latest version. You can get it like this:

```
aider --upgrade

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed aider-chat
```

If you have a chance to try it, let me know if it works better for you.
