### ISSUE TITLE
Install Error: requirements to build wheel do not run successfully

### ISSUE THREAD

**Issue by KagemniKarimu** [Aider-AI/aider#2360]
### Issue

Nearing the final stages of installation on `Linux fedora-workstation 6.11.7-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov  8 19:23:10 UTC 2024 x86_64 GNU/Linux` after trying _the following commands:_

- `python -m pip install -U aider-chat`
- `sudo python -m pip install -U aider-chat`
- `python -m pip install -U --upgrade-strategy only-if-needed aider-chat`
- `sudo python -m pip install -U --upgrade-strategy only-if-needed aider-chat`

Always results in the same **error**:

```
 Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/usr/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
        File "/usr/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
        File "/usr/lib64/python3.13/importlib/__init__.py", line 88, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-u5zp706h/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-u5zp706h/overlay/lib/python3.13/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-u5zp706h/overlay/lib/python3.13/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Version and model info

Python 3.13.0
Fedora 41
git version 2.47.0

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider currently supports Python 3.9-3.12. Not 3.13.

**Comment by Joel-Schaerer-Clario** [comment]
@paul-gauthier is there an issue to follow for 3.13 support?

**Comment by KagemniKarimu** [comment]
Thank you for swift response :tada: 

Just FYI for any other users of Fedora encountering issues with creating virtual environments of python with the correct version: The `--clear` flag is your friend when using the `venv` command.

```BASH

#install the appropriate version
sudo dnf install python3.12

#create a virtual environment with the appropriate version
python3.12 -m venv aider-env --clear

#activate the virtual environment
source aider-env/bin/activate

#verify that you're using python from virtual environment (should be aider-env)
which python

#verify that you're using correct python version (<3.13)
python --version

#install aider
python -m pip install -U aider-chat
```
