### ISSUE TITLE
Uncaught PermissionError in netutil.py line 162

### ISSUE THREAD

**Issue by sir-kokabi** [Aider-AI/aider#2380]
Aider version: 0.63.1
Python version: 3.11.7
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: Yes
OS: Windows 10 (64bit)
Git version: git version 2.44.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 534, in main
    launch_gui(argv)
  File "main.py", line 222, in launch_gui
    cli.main(st_args)
  File "core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cli.py", line 238, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "cli.py", line 274, in _main_run
    bootstrap.run(file, is_hello, args, flag_options)
  File "bootstrap.py", line 326, in run
    asyncio.run(run_server())
  File "runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "bootstrap.py", line 314, in run_server
    await server.start()
  File "server.py", line 275, in start
    start_listening(app)
  File "server.py", line 132, in start_listening
    start_listening_tcp_socket(http_server)
  File "server.py", line 199, in start_listening_tcp_socket
    http_server.listen(port, address)
  File "tcpserver.py", line 183, in listen
    sockets = bind_sockets(
              ^^^^^^^^^^^^^
  File "netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Is this reproducible? How did you trigger it?

**Comment by sir-kokabi** [comment]
I got this error when I ran the `aider --browser` command. I managed to solve it by changing the port, but I don't remember if I changed the port for `litellm cli` or for `aider`. I don't even remember how or where I did this. Anyway, there is no problem now. But I think it's better if `aider` automatically chooses another port when it sees a port is already in use.
