### ISSUE TITLE
Uncaught ImportError in utils.py line 9

### ISSUE THREAD

**Issue by PierrunoYT** [Aider-AI/aider#2389]
Aider version: 0.62.1
Python version: 3.11.0
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.47.0.windows.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 622, in main
    main_model = models.Model(
                 ^^^^^^^^^^^^^
  File "models.py", line 769, in __init__
    res = self.validate_environment()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 973, in validate_environment
    res = litellm.validate_environment(model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "llm.py", line 23, in __getattr__
    self._load_litellm()
  File "llm.py", line 30, in _load_litellm
    self._lazy_module = importlib.import_module("litellm")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "__init__.py", line 10, in <module>
    from litellm.caching.caching import Cache, DualCache, RedisCache, InMemoryCache
  File "__init__.py", line 1, in <module>
    from .caching import Cache, LiteLLMCacheType
  File "caching.py", line 40, in <module>
    from litellm.types.utils import all_litellm_params
  File "utils.py", line 9, in <module>
    from openai.types.completion_usage import (
ImportError: cannot import name 'CompletionTokensDetails' from 'openai.types.completion_usage' (C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\types\completion_usage.py)

```

**Comment by PierrunoYT** [comment]
Sorry
