### ISSUE TITLE
Uncaught TypeError in core.pyx line 14

### ISSUE THREAD

**Issue by cosmojg** [Aider-AI/aider#2393]
Aider version: 0.63.2
Python version: 3.12.5
Platform: macOS-14.5-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.5.0 (64bit)
Git version: git version 2.47.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 841, in main
    coder.run()
  File "base_coder.py", line 741, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 784, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1249, in send_message
    self.reply_completed()
  File "architect_coder.py", line 43, in reply_completed
    editor_coder.run(with_message=content, preproc=False)
  File "base_coder.py", line 735, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 784, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1275, in send_message
    lint_errors = self.lint_edited(edited)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1370, in lint_edited
    errors = self.linter.lint(self.abs_root_path(fname))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 116, in lint
    res += tree_context(rel_fname, code, lintres.lines)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 237, in tree_context
    context = TreeContext(
              ^^^^^^^^^^^^
  File "grep_ast.py", line 47, in __init__
    parser = get_parser(lang)
             ^^^^^^^^^^^^^^^^
  File "core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)

```

**Comment by cosmojg** [comment]
Seems to have been caused by a dependency conflict. Fixed by reinstalling aider with `pip install --upgrade aider-chat`
