### ISSUE TITLE
Uncaught Timeout in exception_mapping_utils.py line 483

### ISSUE THREAD

**Issue by ChrisRutherfordSW2** [Aider-AI/aider#2398]
Aider version: 0.63.0
Python version: 3.10.14
Platform: Linux-5.15.0-119-generic-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: No
OS: Linux 5.15.0-119-generic (64bit)
Git version: git version 2.34.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "default.py", line 72, in map_httpcore_exceptions
    yield
  File "default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "connection_pool.py", line 216, in handle_request
    raise exc from None
  File "connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "connection.py", line 99, in handle_request
    raise exc
  File "connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "http_handler.py", line 371, in post
    response = self.client.send(req, stream=stream)
  File "_client.py", line 926, in send
    response = self._send_handling_auth(
  File "_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "handler.py", line 565, in completion
    response = client.post(
  File "http_handler.py", line 375, in post
    raise litellm.Timeout(
litellm.exceptions.Timeout: litellm.Timeout: Connection timed out after 600.0 seconds.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1755, in completion
    response = anthropic_chat_completions.completion(
  File "handler.py", line 580, in completion
    raise AnthropicError(
litellm.llms.anthropic.common_utils.AnthropicError: litellm.Timeout: Connection timed out after 600.0 seconds.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 832, in main
    coder.run()
  File "base_coder.py", line 741, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 784, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1264, in send_message
    saved_message = self.auto_commit(edited)
  File "base_coder.py", line 1966, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, aider_edits=True)
  File "repo.py", line 110, in commit
    commit_message = self.get_commit_message(diffs, context)
  File "repo.py", line 195, in get_commit_message
    commit_message = simple_send_with_retries(
  File "sendchat.py", line 73, in simple_send_with_retries
    _hash, response = send_completion(**kwargs)
  File "sendchat.py", line 51, in send_completion
    res = litellm.completion(**kwargs)
  File "utils.py", line 1013, in wrapper
    raise e
  File "utils.py", line 903, in wrapper
    result = original_function(*args, **kwargs)
  File "main.py", line 2999, in completion
    raise exception_type(
  File "exception_mapping_utils.py", line 2116, in exception_type
    raise e
  File "exception_mapping_utils.py", line 483, in exception_type
    raise Timeout(
litellm.exceptions.Timeout: litellm.Timeout: AnthropicException - litellm.Timeout: Connection timed out after 600.0 seconds.

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
