### ISSUE TITLE
Uncaught ModuleNotFoundError in <frozen importlib._bootstrap> line 1142

### ISSUE THREAD

**Issue by louay-075** [Aider-AI/aider#2400]
Aider version: 0.63.1
Python version: 3.11.3
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.41.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 832, in main
  File "base_coder.py", line 741, in run
  File "base_coder.py", line 778, in run_one
  File "base_coder.py", line 767, in preproc_user_input
  File "commands.py", line 241, in run
  File "commands.py", line 213, in do_run
  File "commands.py", line 989, in cmd_help
  File "help.py", line 141, in __init__
  File "help.py", line 109, in get_index
  File "help.py", line 34, in get_package_files
  File "_common.py", line 46, in wrapper
    return func(anchor)
           ^^^^^^^^^^^^
  File "_common.py", line 56, in files
    return from_package(resolve(anchor))
                        ^^^^^^^^^^^^^^^
  File "functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_common.py", line 82, in _
    return importlib.import_module(cand)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'aider.website'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. 

How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
