### ISSUE TITLE
Uncaught PermissionError in history.py line 299

### ISSUE THREAD

**Issue by aagulled** [Aider-AI/aider#2454]
Aider version: 0.64.1
Python version: 3.12.3
Platform: Linux-6.8.0-49-generic-x86_64-with-glibc2.39
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.8.0-49-generic (64bit)
Git version: git version 2.43.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 861, in main
    coder.run()
  File "base_coder.py", line 741, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 784, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1294, in send_message
    shared_output = self.run_shell_commands()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 2030, in run_shell_commands
    output = self.handle_shell_commands(command, group)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 2059, in handle_shell_commands
    self.io.add_to_input_history(f"/run {command.strip()}")
  File "io.py", line 489, in add_to_input_history
    FileHistory(self.input_history_file).append_string(inp)
  File "history.py", line 76, in append_string
    self.store_string(string)
  File "history.py", line 299, in store_string
    with open(self.filename, "ab") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '.aider.input.history'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
