### ISSUE TITLE
Uncaught RuntimeError in module.py line 1150

### ISSUE THREAD

**Issue by sanity** [Aider-AI/aider#2474]
Aider version: 0.65.1
Python version: 3.10.12
Platform: Linux-6.8.0-31-generic-x86_64-with-glibc2.39
Python implementation: CPython
Virtual environment: No
OS: Linux 6.8.0-31-generic (64bit)
Git version: git version 2.43.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 887, in main
    coder.run()
  File "base_coder.py", line 758, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 795, in run_one
    message = self.preproc_user_input(user_message)
  File "base_coder.py", line 784, in preproc_user_input
    return self.commands.run(inp)
  File "commands.py", line 251, in run
    return self.do_run(command, rest_inp)
  File "commands.py", line 223, in do_run
    return cmd_method(args)
  File "commands.py", line 984, in cmd_help
    self.help = Help()
  File "help.py", line 139, in __init__
    Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
  File "base.py", line 150, in __init__
    model = SentenceTransformer(
  File "SentenceTransformer.py", line 347, in __init__
    self.to(device)
  File "module.py", line 1152, in to
    return self._apply(convert)
  File "module.py", line 802, in _apply
    module._apply(fn)
  File "module.py", line 802, in _apply
    module._apply(fn)
  File "module.py", line 802, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "module.py", line 825, in _apply
    param_applied = fn(param)
  File "module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. 

How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
