### ISSUE TITLE
Uncaught TypeError in _impl.py line 54

### ISSUE THREAD

**Issue by general-computer** [Aider-AI/aider#2509]
After making a manual commit and reopening Aider, I was unable to refresh the repo map with /map-refresh, seeing: 
Updating repo map 
Unable to count tokens: attrib() got an unexpected keyword argument 'eq'                

____ Aider automatic dump below
Aider version: 0.66.0
Python version: 3.9.20
Platform: macOS-15.1.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 24.1.0 (64bit)
Git version: git version 2.42.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 930, in main
    coder.run()
  File "base_coder.py", line 789, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 832, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1211, in send_message
    litellm_ex = LiteLLMExceptions()
  File "exceptions.py", line 55, in __init__
    self._load()
  File "exceptions.py", line 58, in _load
    import litellm
  File "__init__.py", line 9, in <module>
    from litellm.llms.custom_httpx.http_handler import AsyncHTTPHandler, HTTPHandler
  File "http_handler.py", line 6, in <module>
    import httpx
  File "__init__.py", line 2, in <module>
    from ._api import *
  File "_api.py", line 6, in <module>
    from ._client import Client
  File "_client.py", line 32, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "__init__.py", line 3, in <module>
    from .default import *
  File "default.py", line 33, in <module>
    import httpcore
  File "__init__.py", line 1, in <module>
    from ._api import request, stream
  File "_api.py", line 7, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "connection.py", line 14, in <module>
    from .._synchronization import Lock
  File "_synchronization.py", line 12, in <module>
    import trio
  File "__init__.py", line 18, in <module>
    from ._core import (
  File "__init__.py", line 27, in <module>
    from ._run import (
  File "_run.py", line 22, in <module>
    from outcome import Error, Outcome, Value, capture
  File "__init__.py", line 3, in <module>
    from ._impl import Error, Outcome, Value, acapture, capture
  File "_impl.py", line 39, in <module>
    class Outcome(abc.ABC):
  File "_impl.py", line 54, in Outcome
    _unwrapped = attr.ib(default=False, eq=False, init=False)
TypeError: attrib() got an unexpected keyword argument 'eq'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. 

How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by general-computer** [comment]
Thank you very much for the response! 

I did indeed end up solving this by clearing and reinstalling my python environment, so I've started using pyenv and hope to not file anything in this vein again
