### ISSUE TITLE
Uncaught UnicodeEncodeError in utils.py line 296

### ISSUE THREAD

**Issue by przemek286** [Aider-AI/aider#2529]
Aider version: 0.65.1
Python version: 3.10.12
Platform: Linux-6.8.0-49-generic-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.8.0-49-generic (64bit)
Git version: git version 2.34.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 600, in main
    check_version(io, verbose=args.verbose)
  File "versioncheck.py", line 112, in check_version
    install_upgrade(io, latest_version)
  File "versioncheck.py", line 49, in install_upgrade
    success = utils.check_pip_install_extra(
  File "utils.py", line 353, in check_pip_install_extra
    success, output = run_install(cmd)
  File "utils.py", line 251, in run_install
    spinner.step()
  File "utils.py", line 287, in step
    self._step()
  File "utils.py", line 296, in _step
    print(f"\r{self.text} {next(self.spinner_chars)}\r{self.text} ", end="", flush=True)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u280b' in position 15: ordinal not in range(256)

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.
