### ISSUE TITLE
--watch-files not understanding all JS file-formats ( jsx, 

### ISSUE THREAD

**Issue by hux** [Aider-AI/aider#2547]
### Issue

`Processing your request...
Unknown language for frontend/src/views/events/EventDetail.jsx
Traceback (most recent call last):
  File "/Users/b/me/devenv/venv/lib/python3.11/site-packages/aider/io.py", line 490, in get_input
    cmd = self.file_watcher.process_changes()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/b/me/devenv/venv/lib/python3.11/site-packages/aider/watch.py", line 197, in process_changes
    context = TreeContext(
              ^^^^^^^^^^^^
  File "/Users/b/me/devenv/venv/lib/python3.11/site-packages/grep_ast/grep_ast.py", line 44, in __init__
    raise ValueError(f"Unknown language for {filename}")
ValueError: Unknown language for frontend/src/views/events/EventDetail.jsx`

`Processing your request...
Unknown language for frontend/src/views/artists/ArtistDetail.jsx
Traceback (most recent call last):
  File "/Users/b/me/devenv/venv/lib/python3.11/site-packages/aider/io.py", line 490, in get_input
    cmd = self.file_watcher.process_changes()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/b/me/devenv/venv/lib/python3.11/site-packages/aider/watch.py", line 197, in process_changes
    context = TreeContext(
              ^^^^^^^^^^^^
  File "/Users/b/me/devenv/venv/lib/python3.11/site-packages/grep_ast/grep_ast.py", line 44, in __init__
    raise ValueError(f"Unknown language for {filename}")
ValueError: Unknown language for frontend/src/views/artists/ArtistDetail.jsx`

# Steps to reproduce:

Execute aider with watch files enabled:
`cd mycoderepo && aider --watch-files`

Then in a different terminal, add the line:

`// render an icon for a little person right here AI!`

to a .**jsx** reactJS file, and it fails.

Python works just fine with my django application:

`# Add a model for a personal notes system AI!`

And it works fine if I rename the jsx files to .js 

.ts AND .tsx also work fine, it just seems to be .jsx that fails on files that were previously detectable as JS ( when using non-watch-files mode )

### Version and model info

Aider v0.67 - Sonnet

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by hux** [comment]
Confirmed working! Thank you!
