### ISSUE TITLE
Unknown language for *.sh

### ISSUE THREAD

**Issue by you-n-g** [Aider-AI/aider#2558]
### Issue

![image](https://github.com/user-attachments/assets/f6b74f2c-01b7-4ee0-ae42-3c1ea5268f63)

```
Processing your request...                                                                                                                                                                               
  Unknown language for relaunch_tool.sh                                                                                                                                                                    
  Traceback (most recent call last):                                                                                                                                                                       
    File "/home/xiaoyang/miniconda3/lib/python3.11/site-packages/aider/io.py", line 490, in get_input                                                                                                      
      cmd = self.file_watcher.process_changes()                                                                                                                                                            
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                            
    File "/home/xiaoyang/miniconda3/lib/python3.11/site-packages/aider/watch.py", line 197, in process_changes                                                                                             
      context = TreeContext(                                                                                                                                                                               
                ^^^^^^^^^^^^                                                                                                                                                                               
    File "/home/xiaoyang/miniconda3/lib/python3.11/site-packages/grep_ast/grep_ast.py", line 44, in __init__                                                                                               
      raise ValueError(f"Unknown language for {filename}")                                                                                                                                                 
  ValueError: Unknown language for relaunch_tool.sh 
```

It seems shell script is not considered in /home/xiaoyang/miniconda3/lib/python3.11/site-packages/grep_ast/grep_ast.py

It will raise error when I use `--watch-files` trigger aider.

### Version and model info

aider 0.67.0

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by you-n-g** [comment]
It works on main branch, thanks so much!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
