### ISSUE TITLE
Uncaught PyperclipException in __init__.py line 295

### ISSUE THREAD

**Issue by apmmfg** [Aider-AI/aider#2607]
This is a headless server so error not surprising but could be handled better. maybe simple message "headless server dink! no clipboard"

Aider version: 0.68.0
Python version: 3.11.4
Platform: Linux-5.10.0-33-amd64-x86_64-with-glibc2.31
Python implementation: CPython
Virtual environment: No
OS: Linux 5.10.0-33-amd64 (64bit)
Git version: git version 2.30.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 983, in main
    coder.run()
  File "base_coder.py", line 801, in run
    self.copy_context()
  File "base_coder.py", line 812, in copy_context
    self.commands.cmd_copy_context()
  File "commands.py", line 1446, in cmd_copy_context
    pyperclip.copy(markdown)
  File "__init__.py", line 622, in lazy_load_stub_copy
    return copy(text)
           ^^^^^^^^^^
  File "__init__.py", line 295, in __call__
    raise PyperclipException('Pyperclip could not find a copy/paste mechanism for your system. For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error' + additionalInfo)
pyperclip.PyperclipException: Pyperclip could not find a copy/paste mechanism for your system. For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error
On Linux, you can run `sudo apt-get install xclip` or `sudo apt-get install xselect` to install a copy/paste mechanism.

```

**Comment by paul-gauthier** [comment]
Good point. A fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.
