### ISSUE TITLE
Uncaught ValueError in pathlib.py line 654

### ISSUE THREAD

**Issue by AjayKMehta** [Aider-AI/aider#2619]
Aider version: 0.68.0
Python version: 3.12.7
Platform: Windows-11-10.0.26100-SP0
Python implementation: CPython
Virtual environment: Yes
OS: Windows 11 (64bit)
Git version: git version 2.47.1.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 983, in main
    coder.run()
  File "base_coder.py", line 803, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 850, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1217, in send_message
    chunks = self.format_messages()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1151, in format_messages
    chunks = self.format_chat_chunks()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1098, in format_chat_chunks
    chunks.repo = self.get_repo_messages()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 668, in get_repo_messages
    repo_content = self.get_repo_map()
                   ^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 633, in get_repo_map
    mentioned_fnames.update(self.get_ident_filename_matches(mentioned_idents))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 613, in get_ident_filename_matches
    base = Path(fname).with_suffix("").name.lower()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 654, in with_suffix
    raise ValueError("%r has an empty name" % (self,))
ValueError: WindowsPath('.') has an empty name

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
