### ISSUE TITLE
Uncaught SwitchCoder in commands.py line 1084y

### ISSUE THREAD

**Issue by neorack** [Aider-AI/aider#2662]
Aider version: 0.69.1
Python version: 3.10.11
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.47.1.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 959, in main
    commands.cmd_load(args.load)
  File "commands.py", line 1312, in cmd_load
    self.run(cmd)
  File "commands.py", line 260, in run
    return self.do_run(command, rest_inp)
  File "commands.py", line 232, in do_run
    return cmd_method(args)
  File "commands.py", line 1065, in cmd_architect
    return self._generic_chat_command(args, "architect")
  File "commands.py", line 1084, in _generic_chat_command
    raise SwitchCoder(
aider.commands.SwitchCoder

```

**Comment by ozeron** [comment]
Happened to me as well:
# Uncaught SwitchCoder in commands.py line 1084

Aider version: 0.69.1
Python version: 3.12.2
Platform: macOS-15.1.1-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 24.1.0 (64bit)
Git version: git version 2.47.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 959, in main
    commands.cmd_load(args.load)
  File "commands.py", line 1312, in cmd_load
    self.run(cmd)
  File "commands.py", line 260, in run
    return self.do_run(command, rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 232, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 1065, in cmd_architect
    return self._generic_chat_command(args, "architect")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 1084, in _generic_chat_command
    raise SwitchCoder(
aider.commands.SwitchCoder

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
