### ISSUE TITLE
Bug Report -- Uncaught Timeout in exception_mapping_utils.py line 483

### ISSUE THREAD

**Issue by mudit70** [Aider-AI/aider#2673]
Aider version: 0.69.1
Python version: 3.11.10
Platform: macOS-14.3.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.3.0 (64bit)
Git version: git version 2.39.2 (Apple Git-143)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "default.py", line 72, in map_httpcore_exceptions
    yield
  File "default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "connection_pool.py", line 256, in handle_request
    raise exc from None
  File "connection_pool.py", line 236, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "http11.py", line 136, in handle_request
    raise exc
  File "http11.py", line 106, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "http11.py", line 177, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "http11.py", line 217, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sync.py", line 126, in read
    with map_exceptions(exc_map):
  File "contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "http_handler.py", line 451, in post
    response = self.client.send(req, stream=stream)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "handler.py", line 453, in completion
    response = client.post(
               ^^^^^^^^^^^^
  File "http_handler.py", line 455, in post
    raise litellm.Timeout(
litellm.exceptions.Timeout: litellm.Timeout: Connection timed out after 600.0 seconds.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1775, in completion
    response = anthropic_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "handler.py", line 468, in completion
    raise AnthropicError(
litellm.llms.anthropic.common_utils.AnthropicError: litellm.Timeout: Connection timed out after 600.0 seconds.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 996, in main
    coder.run()
  File "base_coder.py", line 806, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 853, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1350, in send_message
    saved_message = self.auto_commit(edited)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 2062, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, aider_edits=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 119, in commit
    commit_message = self.get_commit_message(diffs, context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 204, in get_commit_message
    commit_message = simple_send_with_retries(model, messages)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 74, in simple_send_with_retries
    _hash, response = send_completion(**kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 51, in send_completion
    res = litellm.completion(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 972, in wrapper
    raise e
  File "utils.py", line 853, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 3066, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "exception_mapping_utils.py", line 2137, in exception_type
    raise e
  File "exception_mapping_utils.py", line 483, in exception_type
    raise Timeout(
litellm.exceptions.Timeout: litellm.Timeout: AnthropicException - litellm.Timeout: Connection timed out after 600.0 seconds.

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
