### ISSUE TITLE
Application is not running. Application.exit() failed

### ISSUE THREAD

**Issue by qrdlgit** [Aider-AI/aider#2716]
### Issue

It seems to be working (it injects the changes) in watch files mode but getting this error when i make a change in --watch-files mode

I do have to press enter in the aider terminal to get it proceed though, not sure if that is normal

File "[REDACTED]/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "[REDACTED]/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "[REDACTED]/.local/share/uv/tools/aider-chat/lib/python3.12/site-packages/aider/watch.py", line 130, in watch_files
    raise e
  File "[REDACTED]/.local/share/uv/tools/aider-chat/lib/python3.12/site-packages/aider/watch.py", line 125, in watch_files
    self.io.interrupt_input()
  File "[REDACTED]/.local/share/uv/tools/aider-chat/lib/python3.12/site-packages/aider/io.py", line 397, in interrupt_input
    self.prompt_session.app.exit()
  File "[REDACTED]/.local/share/uv/tools/aider-chat/lib/python3.12/site-packages/prompt_toolkit/application/application.py", line 1289, in exit
    raise Exception("Application is not running. Application.exit() failed.")

### Version and model info

Aider v0.70.0
Model: deepseek/deepseek-coder with diff edit format, prompt cache, infinite 
output
Git repo: .git with 0 files
Repo-map: using 1024 tokens, auto refresh

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Are you able to reproduce this error?

**Comment by qrdlgit** [comment]
Yes, it happens everytime.  It works as I mentioned above, though I have to hit enter in terminal.

**Comment by paul-gauthier** [comment]
How did you install aider? What OS/environment are you using?

**Comment by qrdlgit** [comment]
I installed aider using pip and aider-install as per the instructions.  I tried fixing it by uninstalling and then reinstalling, but didn't seem to help. 

I am using linux ubuntu.

**Comment by qrdlgit** [comment]
Feel free to close this if no one else reports it.  I tried googling around but didn't see anyone else say anything.  It could be something wrong with my environment.

**Comment by bard** [comment]
Happening here as well when enabling the `--watch-files` feature.

```
> Exception in thread Thread-2 (watch_files):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bard/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/watch.py", line 130, in watch_files
    raise e
  File "/home/bard/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/watch.py", line 125, in watch_files
    self.io.interrupt_input()
  File "/home/bard/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/io.py", line 397, in interrupt_input
    self.prompt_session.app.exit()
  File "/home/bard/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/prompt_toolkit/application/application.py", line 1289, in exit
    raise Exception("Application is not running. Application.exit() failed.")
Exception: Application is not running. Application.exit() failed.
```

**Comment by paul-gauthier** [comment]
The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by bard** [comment]
Thanks for looking into this.

It didn't appear to make a difference:

```
> Exception in thread Thread-2 (watch_files):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bard/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/watch.py", line 131, in watch_files
    raise e
  File "/home/bard/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/watch.py", line 126, in watch_files
    self.io.interrupt_input()
  File "/home/bard/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/io.py", line 397, in interrupt_input
    self.prompt_session.app.exit()
  File "/home/bard/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/prompt_toolkit/application/application.py", line 1289, in exit
    raise Exception("Application is not running. Application.exit() failed.")
Exception: Application is not running. Application.exit() failed.
```

I tried upgrading with:

```
aider --install-main-branch
```

And then with:

```
$ pipx uninstall aider-chat
uninstalled aider-chat! ✨ 🌟 ✨
:~$ pipx install git+https://github.com/Aider-AI/aider.git --python python3.12 
  installed package aider-chat 0.70.1.dev117+gf94e05e0, installed using Python 3.12.8
  These apps are now globally available
    - aider
done! ✨ 🌟 ✨
```

**Comment by paul-gauthier** [comment]
How are you triggering this? How can I reproduce the problem?

**Comment by bard** [comment]
I add the line containing the "ai?" comment to the following file (in a git repo) and save:

```
// what does this function do? ai?

const main = () => {
  console.log("hello, world!");
};
```

I think I've narrowed down the problem. I'm using aider through the [aider.el Emacs interface](https://github.com/tninja/aider.el), and (at least using the latest `main`) the problem occurs in the Emacs interface but not in a terminal. It turns out that what makes the difference is the `TERM` variable. When launching aider in the terminal with `TERM=dumb`, the problem is also triggered:

```
$ TERM=dumb aider --watch-files
───────────────────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────────────────
───
Aider v0.70.1.dev117+gf94e05e0
Main model: gpt-4o-2024-08-06 with diff edit format
Weak model: gpt-4o-mini
Git repo: .git with 0 files
Repo-map: using 1024 tokens, auto refresh
───────────────────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────────────────
───
> Exception in thread Thread-2 (watch_files):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bard/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/wa
tch.py", line 131, in watch_files
    raise e
  File "/home/bard/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/wa
tch.py", line 126, in watch_files
    self.io.interrupt_input()
  File "/home/bard/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/aider/io
.py", line 397, in interrupt_input
    self.prompt_session.app.exit()
  File "/home/bard/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/prompt_t
oolkit/application/application.py", line 1289, in exit
    raise Exception("Application is not running. Application.exit() failed.")
Exception: Application is not running. Application.exit() failed.
```

**Comment by qrdlgit** [comment]
Lol I too use emacs.  Nice catch.

**Comment by paul-gauthier** [comment]
I can't reproduce this even with `TERM=dumb aider`. That indeed causes the output to be laggy/abnormal. But I don't get a crash.

**Comment by bard** [comment]
Hmm. I can understand fancy input, but how is the term type correlated with watching files?

**Comment by paul-gauthier** [comment]
Because watching for file changes needs to be able to interrupt the input prompt which is waiting for the user's next message.
