### ISSUE TITLE
Uncaught AttributeError in main.py line 159

### ISSUE THREAD

**Issue by Wuzzbent** [Aider-AI/aider#2723]
Aider version: 0.70.0
Python version: 3.11.11
Platform: Linux-6.8.0-51-generic-x86_64-with-glibc2.39
Python implementation: CPython
Virtual environment: No
OS: Linux 6.8.0-51-generic (64bit)
Git version: git version 2.43.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 700, in main
    check_gitignore(git_root, io)
  File "main.py", line 159, in check_gitignore
    if repo.ignored(".aider") and repo.ignored(".env"):
       ^^^^^^^^^^^^
AttributeError: 'Repo' object has no attribute 'ignored'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. 

How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html
