### ISSUE TITLE
Uncaught AttributeError in commands.py line 1122

### ISSUE THREAD

**Issue by tomWhiting** [Aider-AI/aider#2737]
Aider version: 0.70.1.dev31+gf292e019
Python version: 3.12.8
Platform: macOS-15.3-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 24.3.0 (64bit)
Git version: git version 2.47.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 1012, in main
    coder.run()
  File "base_coder.py", line 806, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 847, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 836, in preproc_user_input
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 262, in run
    return self.do_run(command, rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 234, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 1122, in cmd_voice
    audio_format=self.voice_format or "wav", device_name=self.voice_input_device
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'Commands' object has no attribute 'voice_format'

```

**Comment by tomWhiting** [comment]
I was able to resolve this by uninstalling the latest version from the main branch and reinstalling using UV version 70.0. Really sorry I'm not sure if the problems at my end I've been running the 'ol girl pretty hard recently.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
