### ISSUE TITLE
litellm.exceptions.APIConnectionError: list index out of range

### ISSUE THREAD

**Issue by sudomain** [Aider-AI/aider#576]
I get this error when trying to get aider to convert a ~50 line Bash script to Python. My Aider is installed via pipx in a Debian PRoot running in Termux.

```
Aider v0.30.1
Model: gemini/gemini-1.5-pro-latest with whole edit format
Git repo: .git with 67 files
Repo-map: using 1024 tokens
Added sss to the chat.
Use /help to see in-chat commands, run with --help to see cmd line args
──────────────────────────────────────────────────────────────────────────────────
sss> This is all written in Bash. I want to change it all to Python and use the prompt toolkit package to do so. Start by writing sss2.py and basing it off of sss

sss

Traceback (most recent call last):
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 9735, in chunk_creator
    if hasattr(chunk.parts[0], "finish_reason"):
               ~~~~~~~~~~~^^^
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/proto/marshal/collections/repeated.py", line 125, in __getitem__
    return self._marshal.to_python(self._pb_type, self.pb[key])
                                                  ~~~~~~~^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 9740, in chunk_creator
    if chunk.parts[0].finish_reason.name == "SAFETY":
       ~~~~~~~~~~~^^^
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/proto/marshal/collections/repeated.py", line 125, in __getitem__
    return self._marshal.to_python(self._pb_type, self.pb[key])
                                                  ~~~~~~~^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 10218, in __next__
    response: Optional[ModelResponse] = self.chunk_creator(chunk=chunk)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 10149, in chunk_creator
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 8703, in exception_type
    raise e
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 8678, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/userr/.local/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/main.py", line 700, in main
    coder.run()
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 397, in run
    new_user_message = self.run_loop()
                       ^^^^^^^^^^^^^^^
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 481, in run_loop
    return self.send_new_user_message(inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 536, in send_new_user_message
    interrupted = self.send(messages, functions=self.functions)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 660, in send
    self.show_send_output_stream(completion)
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/aider/coders/base_coder.py", line 743, in show_send_output_stream
    for chunk in completion:
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 10255, in __next__
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 8703, in exception_type
    raise e
  File "/home/userr/.local/pipx/venvs/aider-chat/lib/python3.11/site-packages/litellm/utils.py", line 8671, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: list index out of ra
nge
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Are you using any sort of firewall or proxy that might be interfering with the Gemini API? As best I can tell, it looks like invalid responses are coming back from the API.

**Comment by sudomain** [comment]
The only thing I use along those lines is Netguard- a per-app firewall/internet permission manager. It shouldn't have though because the app aider is running in (Termux) has full access. Additionally I used aider successfully with other projects with this network config.

**Comment by krrishdholakia** [comment]
Hey @sudomain i've seen this with gemini before. I believe it's a misdirect b/c the responses often work on retrying. I'll map this error correctly

**Comment by paul-gauthier** [comment]
I think this has been resolved in recent versions of litellm/aider. I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by graindorgeanthony** [comment]
Me too!

**Comment by paul-gauthier** [comment]
Can you share the announce lines aider prints when you launch it? And the error output you are seeing.

**Comment by krrishdholakia** [comment]
monitoring this as well

**Comment by paul-gauthier** [comment]
@krrishdholakia ... I just bumped the litellm version that aider uses:

```
-litellm==1.53.9
+litellm==1.58.2
```

https://github.com/Aider-AI/aider/commit/6451d59debfb84f53aa971211e6af916c172bbe3

That change went out with the last release v0.72.0.

**Comment by krrishdholakia** [comment]
got it - is there a repro for this error? gemini seems to work fine for me 

<img width="1223" alt="Image" src="https://github.com/user-attachments/assets/0bfc6698-9a2e-431d-a3e4-b7ce4e4fdc15" />

**Comment by universal** [comment]
was also getting this error using gemini 2.5 pro 05-06. I am trialing it to edit some gams (https://www.gams.com) files.  i forgot to add some content to the actual file, and the file was not added to git yet. it did not make any changes to the empty file. it suggested relatively large changes.

after adding the base content to the file, it successfully did the requested changes. i did get a litellm error afterwards though:

```
Tokens: 18k sent, 5.3k received. Cost: $0.08 message, $0.19 session.
Committing XXXXXXXXXXXXXXX before applying edits.
Commit d7662be feat: Add XXXXXXXXXXX                    
Applied edit to XXXXXXXXXXXXXXXXXXXX
Commit 4386052 feat: XXXXXXXXXXXXXXXXXX             
You can use /undo to undo and discard each aider commit.
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
XXXXXXXXXXXXXXXXXX                                                                                     
> litellm.APIConnectionError: GeminiException - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">                                         
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>

Retrying in 0.2 seconds...

```
